
board: [seeeduino_xiao_ble]
shield: [asym_ble_left rgbled_adapter, asym_ble_right rgbled_adapter,settings_reset]

# include:
#   - board: seeeduino_xiao_ble
#     shield: asym_ble_left
#   - board: seeeduino_xiao_ble
#     shield: asym_ble_right
#   - board: seeeduino_xiao_ble
#     shield: settings_reset
