
board: [seeeduino_xiao_ble]
shield: [asym_ble_left, asym_ble_right,settings_reset, rgbled_adapter]

# include:
#   - board: seeeduino_xiao_ble
#     shield: asym_ble_left
#   - board: seeeduino_xiao_ble
#     shield: asym_ble_right
#   - board: seeeduino_xiao_ble
#     shield: settings_reset