file_format: "1"
id: asym_ble
name: asym_ble
type: shield
url: https://github.com/enzocoralc/Tiny20/
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - asym_left
  - asym_right
