file_format: "1"
id: asym_ble
name: asym_ble
type: shield
url: https://github.com/tamanium/my_zmk_firmware/
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - asym_ble_left
  - asym_ble_right
  